### PR TITLE
Scott Gleaton Waterfall project

### PR DESCRIPTION
**Pull request by sgleaton**
This project is based from my individual project.

### CODE REVIEW

**Comment by kevin-carroll** [comment]
Hi Scott.  Contributing your private project materials to a public, shared information repo is not the proper location.

**Comment by sgleaton** [comment]
I am sorry? what are you talking about?

**Comment by sgleaton** [comment]
I am sorry? what are you talking about?

**Comment by kevin-carroll** [comment]
You had opened a pull request to change the sample_businesss_requirements.md file on monday. It might have been by mistake.

**Comment by sgleaton** [comment]
I did not do that

**Pull request closed without merging**
